local Github = require("updater.github")

describe("github module", function()
  describe("parse_github_url", function()
    it("should parse HTTPS URLs", function()
      local owner, repo = Github.parse_github_url("https://github.com/owner/repo")
      assert.equals("owner", owner)
      assert.equals("repo", repo)
    end)

    it("should parse HTTPS URLs with .git suffix", function()
      local owner, repo = Github.parse_github_url("https://github.com/owner/repo.git")
      assert.equals("owner", owner)
      assert.equals("repo", repo)
    end)

    it("should parse SSH URLs", function()
      local owner, repo = Github.parse_github_url("git@github.com:owner/repo.git")
      assert.equals("owner", owner)
      assert.equals("repo", repo)
    end)

    it("should handle repo names with dots", function()
      local owner, repo = Github.parse_github_url("https://github.com/owner/my.repo")
      assert.equals("owner", owner)
      assert.equals("my.repo", repo)
    end)

    it("should handle repo names with dots and .git suffix", function()
      local owner, repo = Github.parse_github_url("https://github.com/owner/my.repo.git")
      assert.equals("owner", owner)
      assert.equals("my.repo", repo)
    end)

    it("should handle SSH URLs with dotted repo names", function()
      local owner, repo = Github.parse_github_url("git@github.com:owner/my.dotted.repo.git")
      assert.equals("owner", owner)
      assert.equals("my.dotted.repo", repo)
    end)

    it("should return nil for non-GitHub URLs", function()
      local owner, repo = Github.parse_github_url("https://gitlab.com/owner/repo")
      assert.is_nil(owner)
      assert.is_nil(repo)
    end)

    it("should return nil for nil input", function()
      local owner, repo = Github.parse_github_url(nil)
      assert.is_nil(owner)
      assert.is_nil(repo)
    end)
  end)
end)
