local Git = require("updater.git")

describe("version comparison", function()
  describe("compare_version_tags", function()
    it("should return 0 for equal versions", function()
      assert.equals(0, Git.compare_version_tags("v1.0.0", "v1.0.0"))
      assert.equals(0, Git.compare_version_tags("v2.5.3", "v2.5.3"))
    end)

    it("should return 1 when first version is greater", function()
      assert.equals(1, Git.compare_version_tags("v2.0.0", "v1.0.0"))
      assert.equals(1, Git.compare_version_tags("v1.1.0", "v1.0.0"))
      assert.equals(1, Git.compare_version_tags("v1.0.1", "v1.0.0"))
    end)

    it("should return -1 when first version is smaller", function()
      assert.equals(-1, Git.compare_version_tags("v1.0.0", "v2.0.0"))
      assert.equals(-1, Git.compare_version_tags("v1.0.0", "v1.1.0"))
      assert.equals(-1, Git.compare_version_tags("v1.0.0", "v1.0.1"))
    end)

    it("should handle versions without v prefix", function()
      assert.equals(0, Git.compare_version_tags("1.0.0", "1.0.0"))
      assert.equals(1, Git.compare_version_tags("2.0.0", "1.0.0"))
      assert.equals(-1, Git.compare_version_tags("1.0.0", "2.0.0"))
    end)

    it("should handle mixed v prefix", function()
      assert.equals(0, Git.compare_version_tags("v1.0.0", "1.0.0"))
      assert.equals(1, Git.compare_version_tags("v2.0.0", "1.0.0"))
    end)

    it("should handle nil versions", function()
      assert.equals(0, Git.compare_version_tags(nil, nil))
      assert.equals(-1, Git.compare_version_tags(nil, "v1.0.0"))
      assert.equals(1, Git.compare_version_tags("v1.0.0", nil))
    end)

    it("should handle partial versions", function()
      assert.equals(0, Git.compare_version_tags("v1", "v1.0.0"))
      assert.equals(0, Git.compare_version_tags("v1.0", "v1.0.0"))
      assert.equals(1, Git.compare_version_tags("v2", "v1.0.0"))
    end)

    describe("prerelease handling", function()
      it("should treat no prerelease as greater than prerelease", function()
        assert.equals(1, Git.compare_version_tags("v1.0.0", "v1.0.0-pre"))
        assert.equals(1, Git.compare_version_tags("v1.0.0", "v1.0.0-alpha"))
        assert.equals(1, Git.compare_version_tags("v1.0.0", "v1.0.0-beta"))
      end)

      it("should treat prerelease as less than no prerelease", function()
        assert.equals(-1, Git.compare_version_tags("v1.0.0-pre", "v1.0.0"))
        assert.equals(-1, Git.compare_version_tags("v1.0.0-alpha", "v1.0.0"))
      end)

      it("should compare prereleases alphabetically", function()
        assert.equals(1, Git.compare_version_tags("v1.0.0-pre2", "v1.0.0-pre1"))
        assert.equals(-1, Git.compare_version_tags("v1.0.0-pre1", "v1.0.0-pre2"))
        assert.equals(1, Git.compare_version_tags("v1.0.0-beta", "v1.0.0-alpha"))
      end)

      it("should return 0 for equal prereleases", function()
        assert.equals(0, Git.compare_version_tags("v1.0.0-pre", "v1.0.0-pre"))
        assert.equals(0, Git.compare_version_tags("v1.0.0-alpha1", "v1.0.0-alpha1"))
      end)

      it("should compare base version before prerelease", function()
        assert.equals(1, Git.compare_version_tags("v1.1.0-pre", "v1.0.0"))
        assert.equals(-1, Git.compare_version_tags("v1.0.0-pre", "v1.1.0"))
      end)
    end)
  end)
end)
